# Generated by Django 5.1.6 on 2025-02-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_cycledata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('date_logged', models.DateField(auto_now_add=True)),
                ('period_days', models.JSONField()),
            ],
        ),
    ]
