# Generated by Django 5.1.6 on 2025-02-24 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_periodcycle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PeriodCycle',
        ),
    ]
