# Generated by Django 5.1.6 on 2025-02-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_delete_periodcycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='surname',
        ),
    ]
